theme: jekyll-theme-cayman
title: iPreview
description: iPreview provides Quicklook preview for multiple file types in Macos Finder, Quicklook, Spotlight, such as source code, Markdown, Jupyter, Webp, Avif, 3D model, etc.
